debug: false
trace: false

logging:
  config: classpath:log4j2.xml
  level:
    root: info
    org.springframework: info
    io.github.syakuis: info
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql: off
    org.hibernate.type.descriptor.sql.BasicBinder: off

server:
  port: 8080

spring:
  main:
    banner-mode: console
  messages:
    basename: i18n/message
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        show_sql: false
        format_sql: true