logging:
  level:
    io.github.syakuis: debug
    org.hibernate.SQL: trace
    org.hibernate.type.descriptor.sql: trace
    org.hibernate.type.descriptor.sql.BasicBinder: trace
spring:
  jpa:
    hibernate:
      ddl-auto: create